#!/bin/bash

if [[ -z $IMGS2VIDEO_CFGFILE ]]
then
    echo 'IMGS2VIDEO_CFGFILE env var must be available'
    exit 1
fi
if ! [[ -f $IMGS2VIDEO_CFGFILE ]]
then
    echo "Cfg file $IMGS2VIDEO_CFGFILE does not exist"
    exit 1
fi
source $IMGS2VIDEO_CFGFILE

if [[ $# -ne 0 ]]
then
    echo 'Usage: no args'
    echo 'This script merges available recordings of last 24 hours.'
    echo 'Options are configured in config file, pass filename as $IMGS2VIDEO_CFGFILE env var'
    exit 1
fi

CATLIST=`ls -rt \`find $VIDEODIR/*.$OFMT -mtime -1\` `
echo Catlist generated by cat_lastday.sh: $CATLIST
`dirname $0`/cat.sh ${DAYFILE}_part.$OFMT -- $CATLIST
if [[ $? != 0 ]]
then
    rm ${DAYFILE}_part.$OFMT
    exit 1
fi
mv ${DAYFILE}_part.$OFMT ${DAYFILE}.$OFMT
